#!/bin/sh
APP_DIR=/var/usr/palm/applications/org.webosinternals.virtual-keyboard
MEDIA_BASE=/media/internal/virtual-keyboard
THEMES="themes/remix_ice themes/remix_classic themes/remix_glossy themes/LPC_Dark_Rounded_2e"
SOUNDS=sounds/click1.wav

if [ ! -e ${APP_DIR}/md5sums ]
then
  /usr/bin/ipkg -o /var remove org.webosinternals.virtual-keyboard
  echo "ERROR: md5sums file missing, aborting..."
  exit 1
fi

while read i
do
  file=/`echo $i | awk -F* '{print $2}'`
  if [ ! -e $file ]
  then
    echo "ERROR: Framework file cannot be found: $file"
    echo "List of mojo builtins files:"
    ls /usr/palm/frameworks/mojo/builtins/
    /usr/bin/ipkg -o /var remove org.webosinternals.virtual-keyboard
    exit 1
  fi
  expected=`echo $i | awk '{print $1}'`
  calculated=`md5sum $file | awk '{print $1}'`
  if [ "$expected" != "$calculated" ]
  then
    echo "ERROR: mismatch md5sums"
    echo "       expected: $expected"
    echo "       calculated: $calculated"
    /usr/bin/ipkg -o /var remove org.webosinternals.virtual-keyboard
    exit 1
  fi
done < ${APP_DIR}/md5sums

for i in `/var/usr/bin/diffstat -p1 -l ${APP_DIR}/add-onscreen-keyboard.patch`
do
  grep $i ${APP_DIR}/md5sums
  if [ $? -ne 0 ]
  then
    rm -f /$i
  fi
done

cd / && /var/usr/bin/patch -p1 --dry-run < ${APP_DIR}/add-onscreen-keyboard.patch
if [ $? -ne 0 ]
then
  echo "ERROR: patch dryrun failed, aborting..."
  /usr/bin/ipkg -o /var remove org.webosinternals.virtual-keyboard
  exit 1
fi

# dry-run passed, so patch for real and create backups
/var/usr/bin/patch -p1 -b < ${APP_DIR}/add-onscreen-keyboard.patch

# create md5sums of all patched files, for future removal verifications
rm -f ${APP_DIR}/md5sums.patched
touch ${APP_DIR}/md5sums.patched
for i in `/var/usr/bin/diffstat -p1 -l ${APP_DIR}/add-onscreen-keyboard.patch`
do
  md5sum /$i >> ${APP_DIR}/md5sums.patched
done

# Default themes, sounds and config
if [ ! -d ${MEDIA_BASE} ]
then
  rm -rf ${MEDIA_BASE}
  mv ${APP_DIR}/virtual-keyboard ${MEDIA_BASE}
else
  if [ ! -d ${MEDIA_BASE}/themes ]
  then
    rm -rf ${MEDIA_BASE}/themes
    mv ${APP_DIR}/virtual-keyboard/themes ${MEDIA_BASE}/themes
  else
    for i in ${THEMES}
    do
      rm -rf ${MEDIA_BASE}/$i
      mv ${APP_DIR}/virtual-keyboard/$i ${MEDIA_BASE}/$i
    done
  fi

  if [ ! -d ${MEDIA_BASE}/sounds ]
  then
    rm -rf ${MEDIA_BASE}/sounds
    mv ${APP_DIR}/virtual-keyboard/sounds ${MEDIA_BASE}/sounds
  else
    for i in ${SOUNDS}
    do
      rm -rf ${MEDIA_BASE}/$i
      mv ${APP_DIR}/virtual-keyboard/$i ${MEDIA_BASE}/$i
    done
  fi

  #if [ ! -e ${MEDIA_BASE}/kb_config.json ]
  #then
    mv ${APP_DIR}/virtual-keyboard/kb_config.json ${MEDIA_BASE}/kb_config.json
  #fi
fi

# Restart Luna
if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
    /sbin/stop LunaSysMgr
    /sbin/start LunaSysMgr
fi

exit 0
