#!/bin/sh
MEDIA_BASE=/media/internal/virtual-keyboard
THEMES="themes/remix_ice themes/remix_classic themes/remix_glossy themes/LPC_Dark_Rounded_2e"
SOUNDS=sounds/click1.wav

for i in ${THEMES}
do
  rm -rf ${MEDIA_BASE}/$i
done

for i in ${SOUNDS}
do
  rm -rf ${MEDIA_BASE}/$i
done

exit 0
