#!/bin/sh
APP_DIR=/var/usr/palm/applications/org.webosinternals.virtual-keyboard
PATCH_NAME=add-onscreen-keyboard.patch
FILE_LIST=`diffstat -p0 -l $APP_DIR/$PATCH_NAME`
PATCH_CONTROL_DIR=/var/usr/lib/.webosinternals.patches

do_failure() {
  exit 1
}

/var/usr/bin/patch -R -p1 -d / --dry-run < ${APP_DIR}/$PATCH_NAME || do_failure

/var/usr/bin/patch -R -p1 -d / < ${APP_DIR}/$PATCH_NAME

for i in $FILE_LIST
do
  orig_md5sum=`md5sum $i.webosinternals.orig | awk '{print $1}'`
  file_md5sum=`md5sum $i | awk '{print $1}'`
  if [ "$orig_md5sum" = "$file_md5sum" ]
  then
    rm -f $i.webosinternals.orig
    tmpvar=`echo $i | tr '/' '.'`
    sed -i -e /$tmpvar/d $PATCH_CONTROL_DIR/backups
  fi
done

rm -f $PATCH_CONTROL_DIR/$PATCH_NAME
echo "SUCCESS"

# Restart Luna
if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
    /sbin/stop LunaSysMgr
    /sbin/start LunaSysMgr
fi

rm -rf ${APP_DIR}/*

MEDIA_BASE=/media/internal/virtual-keyboard
THEMES="themes/remix_ice themes/remix_classic themes/remix_glossy themes/LPC_Dark_Rounded_2e"
SOUNDS=sounds/click1.wav

for i in ${THEMES}
do
  rm -rf ${MEDIA_BASE}/$i
done

for i in ${SOUNDS}
do
  rm -rf ${MEDIA_BASE}/$i
done

exit 0
